from datetime import date
from logging import getLogger, INFO, Formatter, FileHandler

"""
Class that manages everything related to the application's
records.
"""
class Logger:
	"""
	Method that writes the logs generated by the application
	in a file.

	Parameters:
	self -- An instantiated object of the Logger class.
	message -- Message to be shown in the log.
	type_log -- Type of log to write.
	"""
	def createSnapToolLog(self, message, type_log):
		name_log = '/var/log/Snap-Tool/snap-tool-log-' + str(date.today()) + '.log'
		logger = getLogger('Snap_Tool_Log')
		logger.setLevel(INFO)
		fh = FileHandler(name_log)
		if (logger.hasHandlers()):
   	 		logger.handlers.clear()
		formatter = Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
		fh.setFormatter(formatter)
		logger.addHandler(fh)
		if type_log == 1:
			logger.info(message)
		if type_log == 2:
			logger.warning(message)
		if type_log == 3:
			logger.error(message)